### ISSUE TITLE
Rename `io.spine.prototap.io.spine.prototap.gradle.plugin` published to GitHub Packages

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/ProtoTap#10]
Currently, ProtoTap Gradle plugin is published to both Gradle plugin portal, and to GitHub Packages. The latter publication [has weird coordinates](https://github.com/SpineEventEngine/ProtoTap/packages/2138371):

```xml

<dependency>
  <groupId>io.spine.prototap</groupId>

  <!--- Note the duplication of the artifact ID: -->
  <artifactId>io.spine.prototap.gradle.plugin</artifactId>
  <version>0.8.7</version>
</dependency>
```

Thus, the resulting "fully qualified" name has the group ID listed twice: `io.spine.prototap.io.spine.prototap.gradle.plugin`.

In scope of this task, we should look into renaming the artifact, so that the group ID remains the same, and the artifact ID looks something like **`spine-prototap-gradle-plugin`**.

Probably, the following code snipped we use in ProtoData, could do the job:

```kotlin
publishing.publications.withType<MavenPublication>().all {
    groupId = "io.spine.prototap"
    artifactId = "spine-prototap-gradle-plugin"
}
```

Please note that the problem is not unique to all of Gradle plugins provided by Spine. We have the same issue with the Chords Gradle plugin, and for the same reasons. Other than that, the rest of our Gradle plugins are published either in a custom way (e.g. via a manually crafted fat JAR), or by skipping the GitHub Packages as a destination (like ProtoData).

**Comment by armiol** [comment]
@yevhenii-nadtochii assigning the next task to you, just in case you don't have anything left on your plate.

@alexander-yevsyukov as discussed, JFYI.

**Comment by yevhenii-nadtochii** [comment]
@armiol Looks like this artifact name is required by Gradle to be able to fetch the plugin by ID from `plugins` section of a build script. Gradle calls it "plugin marker artifact".

Gradle's `com.gradle.plugin-publish` plugin creates two publications:

1. `pluginMaven` that publishes [prototap-gradle-plugin](https://github.com/SpineEventEngine/ProtoTap/packages/2138282) artifact. It contains the plugin's JAR, docs, sources and dependencies.
2. `PluginMarkerMaven` that publishes the mentioned [io.spine.prototap.gradle.plugin](https://github.com/SpineEventEngine/ProtoTap/packages/2138371) artifact. It's actually a bare POM file with a dependency to the actual plugin (1). Its artifact name is derived from the plugin ID and version declared in the script. So build scripts look exactly for the marker in the first place. And only then pick up the actual plugin artifact. [Here](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) is the official docs on this matter.

What about absence of `spine-` prefix for ProtoTap and ProtoData artifacts. Both repositories explicitly declare the prefix (overriding the default `spine-`), and it looks quite intentional: [here](https://github.com/SpineEventEngine/ProtoData/blob/493466105ea704fbd9a7983124aad54d18615f0a/build.gradle.kts#L79) and [here](https://github.com/SpineEventEngine/ProtoTap/blob/49754b873a77f783eb53b6df93c9d76d039c5f14/build.gradle.kts#L65). I can prepend `spine-` there if it is needed.

**Comment by armiol** [comment]
@yevhenii-nadtochii thanks for the clarification. Let's do nothing. Seems to work as designed.
